### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ziyou2** [UISSH/install-script#2]
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Write the database password to the backend config.
Error: near line 1: no such table: common_systemconfig
Sync CORS_ALLOWED_ORIGINS and CSRF_TRUSTED_ORIGINS settings
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    init_backend_settings()
  File "main.py", line 111, in init_backend_settings
    with open(_env_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/uissh/backend/.env'

**Comment by zmaplex** [comment]
提供下运行参数，以及 Linux 发行版

**Comment by zmaplex** [comment]
你好，或者提供下云厂商以及 linux 发行版
